In [1]:
import numpy as np

identity_matrix = np.identity(3)
print("3x3 Identity Matrix:")
print(identity_matrix)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np

matrix = np.arange(2, 18).reshape(4, 4)
print("4x4 Matrix:")
print(matrix)


4x4 Matrix:
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


In [4]:
# User-defined calculator functions

def add(a, b):
    return a + b

def sub(a, b):
    return a - b

# Using the functions
print("Addition:", add(10, 5))
print("Subtraction:", sub(10, 5))


Addition: 15
Subtraction: 5
